# -*- coding: utf-8 -*-
"""Mini2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FrOKezVrl74lnISvwROxEbpHB7-PqfJ6
"""

import tkinter as tk
import random

root = tk.Tk()
root.title("Target Shooting Game")
root.geometry("600x450")

score = 0
time_left = 30
game_running = True

canvas = tk.Canvas(root, width=600, height=350, bg="black")
canvas.pack()

score_label = tk.Label(root, text="Score: 0", font=("Arial", 16))
score_label.pack()

timer_label = tk.Label(root, text="Time: 30", font=("Arial", 16), fg="red")
timer_label.pack()

targets = []

# create a new target (random shape)
def create_target():
    if not game_running:
        return
    x = random.randint(50, 550)
    y = random.randint(50, 300)

    shape_type = random.choice(["circle", "rect", "triangle"])

    if shape_type == "circle":
        target = canvas.create_oval(x, y, x+40, y+40, fill="red", outline="white")
    elif shape_type == "rect":
        target = canvas.create_rectangle(x, y, x+50, y+30, fill="purple", outline="white")
    else:  # triangle
        target = canvas.create_polygon(x, y+40, x+25, y, x+50, y+40, fill="blue", outline="white")

    targets.append(target)
    root.after(2000, lambda: remove_target(target))  # remove target after 2 sec
    root.after(1000, create_target)  # new target every 1 sec

def remove_target(target):
    if target in targets:
        canvas.delete(target)
        targets.remove(target)

# shooting logic
def shoot(event):
    global score
    if not game_running:
        return
    clicked = canvas.find_overlapping(event.x, event.y, event.x, event.y)
    for obj in clicked:
        if obj in targets:
            canvas.delete(obj)
            targets.remove(obj)
            score += 1
            score_label.config(text=f"Score: {score}")

# countdown timer
def countdown():
    global time_left, game_running
    if time_left > 0:
        time_left -= 1
        timer_label.config(text=f"Time: {time_left}")
        root.after(1000, countdown)
    else:
        game_running = False
        canvas.create_text(300, 175, text="⏳ Game Over!", font=("Arial", 30), fill="white")

canvas.bind("<Button-1>", shoot)

# start game
create_target()
countdown()

root.mainloop()